services:
  block-crawler-dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-sharedDb"
  block-crawler-bootstrapper:
    build: ./
    links:
      - block-crawler-dynamodb
    depends_on:
      - block-crawler-dynamodb
    environment:
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?err}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?err}
     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:?err}
     - AWS_DYNAMODB_REGION=${AWS_DYNAMODB_REGION:?err}
    entrypoint: ""
    command: >
      bash -c "echo \"Preparing environment...\"
      && python bin/reset.py --retry http://block-crawler-dynamodb:8000 db
      && echo OK"
